// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmalandsBackend.DataAccess;

#nullable disable

namespace SmalandsBackend.Migrations
{
    [DbContext(typeof(SmalandsDbContext))]
    [Migration("20230131131602_SmalandsNation")]
    partial class SmalandsNation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SmalandsBackend.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gabriella Långbergs",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Ordförande"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Eric Sandberg",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Vice-Ordförande"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Oliver Nordwall",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Ekonomiansvarig"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Andre Franzen",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Festansvarig"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dag Mattson",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Fest-och Utskottsansvarig"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Amanda Sten",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Festansvarig"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Linus Johansson",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Aktivitets-och Utskottsansvarig"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mia Parkkinen",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Aktivitetsansvarig"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mårten Stridh",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Housemoose"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Philip Giselson",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Band och PA"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cornelis Blom",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Band/PA-och Jobbansvarig"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Filippa Lindblom",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Info/Webb/PR"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Josefin Augustson",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Samarbete"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Behiye Kaya",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Samarbete"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Melvin Johnsson",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Sivansansvarig"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Ramazan Soyal",
                            Picture = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Role = "Sivansansvarig"
                        });
                });

            modelBuilder.Entity("SmalandsBackend.Models.image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Generic Image",
                            Height = 50,
                            PictureUrl = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Title = "Test image",
                            Width = 50
                        },
                        new
                        {
                            Id = 2,
                            Description = "Generic Image2",
                            Height = 50,
                            PictureUrl = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Title = "Image",
                            Width = 50
                        },
                        new
                        {
                            Id = 3,
                            Description = "Generic Image3",
                            Height = 50,
                            PictureUrl = "https://i.picsum.photos/id/5/200/300.jpg?hmac=1TWjKFT7_MRP0ApEyDUA3eCP0HXaKTWJfHgVjwGNoZU",
                            Title = "Test imag3",
                            Width = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
